//  oop - obeject oriented programing  is a way of organizing and designing computer programs that emphasize the use of objects, which are instances of classes that contain both data methods. For instance, a car object would have attributes like color, make, and model, and behaviors like accelerating and braking.
// OOP allows you to create reusable and modular code by encapsulating data and the methods that operate on the data within objects. This helps in creating more organized, manageable, and scalable codebases, making it easier to maintain and update large software projects. OOP promotes concepts such as inheritance, polymorphism, and encapsulation, which enable efficient code reuse and provide a more intuitive way of modeling real-world systems and problem domains in software.

//There are four main pillars, or concepts, in object-oriented programming (OOP) that help in designing and implementing programs. These are:

//Abstraction: Abstraction focuses on providing a simplified view of an object or system, highlighting only the necessary attributes and behaviors while hiding the unnecessary details. It allows you to focus on what an object does rather than how it does it, making complex systems more manageable.(means aam khao guttlia na gino)

//Encapsulation: This refers to the bundling of data with the methods that operate on that data. It helps in hiding the internal state of an object from the outside and only exposing the necessary operations or behaviors, promoting data security and modularity. (means jaise ki aapne 5 chijo ko jodhkar ek entity bnai toh bo inheritance hai,eg ek motherboard liya , keyboard liya or display li aur ek laptop tyar kiya.)

//Inheritance: Inheritance enables a class to inherit properties and behavior from another class, establishing a hierarchical relationship between classes. It promotes code reusability and helps to create a new class by extending an existing class, thereby reducing redundancy and promoting a more organized codebase.

//Polymorphism: Polymorphism allows objects of different classes to be treated as objects of a common superclass. It enables a single interface to be used for different data types, reducing the need for multiple conditional statements. Polymorphism can take the form of method overloading or method overriding, facilitating more flexible and adaptable code.(1 chizz different form is polymorphism , jaise ki aapka phone ek smart h camrea v hai , note taking device v h.)